apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config-file
data:
  config.yaml: |
    model_list:
      - model_name: Qwen3.5-9B
        litellm_params:
          model: hosted_vllm/Qwen3.5-9B
          api_base: http://vllm-qwen3-5-9b:8000/v1

      - model_name: Nemotron-3-Ultra-550B-A55B
        litellm_params:
          model: hosted_vllm/Nemotron-3-Ultra-550B-A55B
          api_base: http://vllm-nemotron-3-ultra:8000/v1

      - model_name: Qwen3-Embedding-4B
        litellm_params:
          model: hosted_vllm/Qwen3-Embedding-4B
          api_base: http://vllm-qwen3-embedding-4b:8000/v1
          encoding_format: "float"
        model_info:
          mode: embedding

      - model_name: bge-m3-pooling
        litellm_params:
          model: hosted_vllm/bge-m3
          api_base: http://vllm-bge-m3:8000
        model_info:
          mode: embedding

      - model_name: Qwen3-Reranker-4B
        litellm_params:
          model: hosted_vllm/Qwen3-Reranker-4B
          api_base: http://vllm-qwen3-reranker-4b:8000
        model_info:
          mode: rerank

      - model_name: datalab-to/surya-ocr-2
        litellm_params:
          model: hosted_vllm/datalab-to/surya-ocr-2
          api_base: http://surya-vllm:8000/v1
          api_key: EMPTY

    litellm_settings:
      drop_params: true
