from __future__ import annotations

from copy import deepcopy
from typing import TYPE_CHECKING, Any

from pydantic import Field, PrivateAttr

from config.config import ServerConfig, get_server_config
from dispatcher.base_dispatcher import AbstractDispatcher
from model.document_chunk import DocumentChunk

if TYPE_CHECKING:
    from elasticsearch import Elasticsearch


LANGUAGE_DETECTION_MODEL = "lang_ident_model_1"
DEFAULT_LEXICAL_LANGUAGE = "en"

MODEL_SETTINGS = {
    "service": "custom",
    "task_type": "text_embedding",
    "dimensions": 2560,
    "similarity": "dot_product",
    "element_type": "float",
}

SEMANTIC_TEXT_FIELD = {
    "type": "semantic_text",
    "model_settings": MODEL_SETTINGS,
    "index_options": {
        "dense_vector": {
            "element_type": "float",
            "type": "int8_hnsw",
            "m": 16,
            "ef_construction": 100,
        }
    },
    "chunking_settings": {
        "strategy": "none",
    },
}

CONTENT_LEX_PROPERTIES = {
    "es": {"type": "text", "analyzer": "spanish"},
    "en": {"type": "text", "analyzer": "english"},
    "fr": {"type": "text", "analyzer": "french"},
}

TITLE_FIELD = {
    "type": "text",
    "fields": {
        "keyword": {
            "type": "keyword",
            "ignore_above": 512,
        }
    },
}

OPEN_RAG_MAPPINGS = {
    "dynamic": False,
    "_source": {
        "excludes": [
            "content_lex.*",
            "language_detection",
        ]
    },
    "_meta": {
        "description": (
            "Multilingual RAG mapping adapted to DocumentChunk. The canonical "
            "chunk text is stored once in content as semantic_text. Document "
            "titles are also embedded in title_semantic. Lexical BM25 fields are "
            "generated by the ingest pipeline and excluded from _source."
        ),
        "language_detection_model": LANGUAGE_DETECTION_MODEL,
        "expected_model_settings": MODEL_SETTINGS,
        "chunking": (
            "Automatic semantic_text chunking is disabled because the service "
            "already indexes pre-chunked DocumentChunk records."
        ),
        "lexical_routing": (
            "The ingest pipeline detects language and copies content into exactly "
            "one content_lex.<lang> field for language-specific BM25 analysis."
        ),
        "default_lexical_language": DEFAULT_LEXICAL_LANGUAGE,
        "document_chunk_fields": [
            "content",
            "document_id",
            "chunk_id",
            "chunk_index",
            "chunking_strategy",
            "content_token_count",
            "doc_items",
            "page_number",
            "page_numbers",
            "total_pages",
            "title",
            "title_semantic",
            "source_file_name",
            "raw_text",
        ],
        "supported_lexical_languages": [
            "es",
            "en",
            "fr",
        ],
    },
    "properties": {
        "content": SEMANTIC_TEXT_FIELD,
        "content_lex": {
            "properties": CONTENT_LEX_PROPERTIES,
        },
        "language": {"type": "keyword"},
        "language_probability": {"type": "float"},
        "clean_title": TITLE_FIELD,
        "title": TITLE_FIELD,
        "title_semantic": SEMANTIC_TEXT_FIELD,
        "source_file_name": {
            "type": "keyword",
            "fields": {
                "text": {"type": "text"},
            },
        },
        "record_type": {"type": "keyword"},
        "document_id": {"type": "keyword"},
        "chunk_id": {"type": "keyword"},
        "chunk_index": {"type": "integer"},
        "chunking_strategy": {"type": "keyword"},
        "content_token_count": {"type": "integer"},
        "doc_items": {"type": "keyword"},
        "page_number": {"type": "integer"},
        "page_numbers": {"type": "integer"},
        "total_pages": {"type": "integer"},
        "raw_text": {
            "type": "text",
            "index": False,
        },
        "searchable": {"type": "boolean"},
        "boilerplate": {"type": "boolean"},
        "content_kind": {"type": "keyword"},
        "content_length": {"type": "integer"},
        "ingest_error": {"type": "text"},
        "ingested_at": {"type": "date"},
    },
}

OPEN_RAG_PIPELINE = {
    "description": (
        "Escape inference-template placeholders, detect chunk language, route "
        "canonical content into one language-specific lexical field, and normalize "
        "DocumentChunk metadata."
    ),
    "processors": [
        {
            "set": {
                "field": "ingested_at",
                "value": "{{{_ingest.timestamp}}}",
                "override": False,
            }
        },
        {
            "script": {
                "description": (
                    "Escape Elasticsearch custom inference template placeholders "
                    "in semantic source text."
                ),
                "lang": "painless",
                "source": (
                    "if (ctx.content != null) { "
                    "ctx.content = ctx.content.replace('${', '$ {'); "
                    "} "
                    "if (ctx.title_semantic != null) { "
                    "ctx.title_semantic = ctx.title_semantic.replace('${', '$ {'); "
                    "}"
                ),
            }
        },
        {
            "script": {
                "description": (
                    "Normalize DocumentChunk fields into indexed RAG helper fields."
                ),
                "lang": "painless",
                "source": (
                    "boolean isHex(String value) { "
                    "for (int i = 0; i < value.length(); i++) { "
                    "char c = value.charAt(i); "
                    "if (!((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || "
                    "(c >= 'A' && c <= 'F'))) { return false; } "
                    "} "
                    "return true; "
                    "} "
                    "String stripExtension(String value) { "
                    "String lower = value.toLowerCase(); "
                    "if (lower.endsWith('.pdf')) { "
                    "return value.substring(0, value.length() - 4).trim(); "
                    "} "
                    "if (lower.endsWith('.docx') || lower.endsWith('.pptx') || "
                    "lower.endsWith('.xlsx') || lower.endsWith('.html')) { "
                    "return value.substring(0, value.length() - 5).trim(); "
                    "} "
                    "if (lower.endsWith('.doc') || lower.endsWith('.ppt') || "
                    "lower.endsWith('.xls') || lower.endsWith('.txt') || "
                    "lower.endsWith('.htm')) { "
                    "return value.substring(0, value.length() - 4).trim(); "
                    "} "
                    "if (lower.endsWith('.md')) { "
                    "return value.substring(0, value.length() - 3).trim(); "
                    "} "
                    "return value; "
                    "} "
                    "String cleanTitle(def raw) { "
                    "if (raw == null) { return null; } "
                    "String value = raw.toString().trim(); "
                    "if (value.length() == 0) { return null; } "
                    "int slash = Math.max(value.lastIndexOf('/'), value.lastIndexOf('\\\\')); "
                    "if (slash >= 0 && slash + 1 < value.length()) { "
                    "value = value.substring(slash + 1).trim(); "
                    "} "
                    "if (value.length() > 33 && value.charAt(32) == '-' && "
                    "isHex(value.substring(0, 32))) { "
                    "value = value.substring(33).trim(); "
                    "} else if (value.length() > 37 && value.charAt(8) == '-' && "
                    "value.charAt(13) == '-' && value.charAt(18) == '-' && "
                    "value.charAt(23) == '-' && value.charAt(36) == '-') { "
                    "String compact = value.substring(0, 8) + value.substring(9, 13) + "
                    "value.substring(14, 18) + value.substring(19, 23) + "
                    "value.substring(24, 36); "
                    "if (isHex(compact)) { value = value.substring(37).trim(); } "
                    "} "
                    "value = stripExtension(value); "
                    "return value.length() == 0 ? null : value; "
                    "} "
                    "if (ctx.record_type == null) { ctx.record_type = 'chunk'; } "
                    "String title = cleanTitle(ctx.title); "
                    "String cleanedTitle = cleanTitle(ctx.clean_title); "
                    "String semanticTitle = cleanTitle(ctx.title_semantic); "
                    "if (title != null) { ctx.title = title; } "
                    "if (cleanedTitle == null) { cleanedTitle = title; } "
                    "if (cleanedTitle != null) { ctx.clean_title = cleanedTitle; } "
                    "if (semanticTitle == null) { semanticTitle = cleanedTitle; } "
                    "if (semanticTitle != null) { ctx.title_semantic = semanticTitle; } "
                    "if (ctx.title == null && cleanedTitle != null) { "
                    "ctx.title = cleanedTitle; "
                    "} "
                    "if (ctx.content != null) { "
                    "ctx.content_length = ctx.content.length(); "
                    "} "
                    "if (ctx.searchable == null) { ctx.searchable = true; } "
                    "if (ctx.boilerplate == null) { ctx.boilerplate = false; } "
                    "if (ctx.content_kind == null) { ctx.content_kind = 'chunk'; }"
                ),
            }
        },
        {
            "inference": {
                "if": "ctx.content != null && ctx.content.length() > 0",
                "model_id": LANGUAGE_DETECTION_MODEL,
                "field_map": {
                    "content": "text",
                },
                "inference_config": {
                    "classification": {
                        "num_top_classes": 3,
                    }
                },
                "target_field": "language_detection",
            }
        },
        {
            "script": {
                "description": (
                    "Choose a supported lexical analyzer field and copy content "
                    "into exactly one content_lex.<language> field."
                ),
                "lang": "painless",
                "source": (
                    "def supported = ['es', 'en', 'fr']; "
                    "def lang = null; "
                    "double prob = 0.0; "
                    "if (ctx.language_detection != null) { "
                    "if (ctx.language_detection.predicted_value != null) { "
                    "lang = ctx.language_detection.predicted_value; "
                    "} "
                    "if (ctx.language_detection.top_classes != null && "
                    "ctx.language_detection.top_classes.size() > 0 && "
                    "ctx.language_detection.top_classes[0].class_probability "
                    "!= null) { "
                    "prob = ctx.language_detection.top_classes[0].class_probability; "
                    "} "
                    "} "
                    "if (lang == null || lang == 'zxx' || prob < 0.60 || "
                    "!supported.contains(lang)) { lang = '"
                    f"{DEFAULT_LEXICAL_LANGUAGE}"
                    "'; } "
                    "ctx.language = lang; "
                    "ctx.language_probability = prob; "
                    "if (ctx.content != null) { "
                    "if (ctx.content_lex == null) { ctx.content_lex = new HashMap(); } "
                    "ctx.content_lex[lang] = ctx.content; "
                    "}"
                ),
            }
        },
        {
            "remove": {
                "field": [
                    "content_semantic",
                    "language_detection",
                    "chunker_strategy",
                ],
                "ignore_missing": True,
            }
        },
    ],
    "on_failure": [
        {
            "set": {
                "field": "ingest_error",
                "value": "{{{ _ingest.on_failure_message }}}",
            }
        }
    ],
}


def build_open_rag_mappings(inference_id: str) -> dict[str, Any]:
    mappings = deepcopy(OPEN_RAG_MAPPINGS)
    mappings["_meta"]["inference_id"] = inference_id
    mappings["properties"]["content"] = deepcopy(SEMANTIC_TEXT_FIELD)
    mappings["properties"]["title_semantic"] = deepcopy(SEMANTIC_TEXT_FIELD)
    mappings["properties"]["content"]["inference_id"] = inference_id
    mappings["properties"]["title_semantic"]["inference_id"] = inference_id
    return mappings


class ElasticsearchDispatch(AbstractDispatcher):
    """Dispatcher skeleton backed by the Elasticsearch Python client."""

    hosts: list[str] = Field(default_factory=list)
    api_key: str | None = None
    index_name: str
    pipeline_name: str
    inference_id: str
    verify_certs: bool
    ssl_show_warn: bool
    http_compress: bool
    bulk_api_timeout: str
    bulk_request_timeout_seconds: int
    bulk_batch_size: int
    bulk_max_retries: int

    _client: Elasticsearch = PrivateAttr()

    def __init__(
        self,
        server_config: ServerConfig | None = None,
        **data: object,
    ) -> None:
        config = server_config or get_server_config()
        config_data: dict[str, object] = {
            "hosts": config.elastic_hosts,
            "api_key": config.elastic_api_key,
            "index_name": config.elastic_index_name,
            "pipeline_name": config.elastic_pipeline_name,
            "inference_id": config.elastic_inference_id,
            "verify_certs": config.elastic_verify_certs,
            "ssl_show_warn": config.elastic_ssl_show_warn,
            "http_compress": config.elastic_http_compress,
            "bulk_api_timeout": config.elastic_bulk_api_timeout,
            "bulk_request_timeout_seconds": config.elastic_bulk_request_timeout_seconds,
            "bulk_batch_size": config.elastic_bulk_batch_size,
            "bulk_max_retries": config.elastic_bulk_max_retries,
        }
        config_data.update(data)
        super().__init__(**config_data)
        self._client = self._build_client()
        self._ensure_pipeline()
        self._ensure_index()

    def _build_client(self) -> Elasticsearch:
        from elasticsearch import Elasticsearch

        client_options = {
            "hosts": self.hosts,
            "verify_certs": self.verify_certs,
            "ssl_show_warn": self.ssl_show_warn,
            "http_compress": self.http_compress,
        }
        if self.api_key is None:
            return Elasticsearch(**client_options)
        return Elasticsearch(**client_options, api_key=self.api_key)

    def _ensure_pipeline(self) -> None:
        pipeline = deepcopy(OPEN_RAG_PIPELINE)
        self._client.ingest.put_pipeline(
            id=self.pipeline_name,
            description=pipeline["description"],
            processors=pipeline["processors"],
            on_failure=pipeline["on_failure"],
        )

    def _ensure_index(self) -> None:
        if bool(self._client.indices.exists(index=self.index_name)):
            self._ensure_index_mappings()
            return

        self._client.indices.create(
            index=self.index_name,
            settings={
                "index.default_pipeline": self.pipeline_name,
            },
            mappings=build_open_rag_mappings(self.inference_id),
        )

    def _ensure_index_mappings(self) -> None:
        if self._mapping_field_exists("title_semantic"):
            return

        mappings = build_open_rag_mappings(self.inference_id)
        self._client.indices.put_mapping(
            index=self.index_name,
            properties={
                "title_semantic": mappings["properties"]["title_semantic"],
            },
        )

    def _mapping_field_exists(self, field_name: str) -> bool:
        response = self._client.indices.get_mapping(index=self.index_name)
        response_body = getattr(response, "body", response)
        index_mapping = response_body.get(self.index_name)
        if index_mapping is None and response_body:
            index_mapping = next(iter(response_body.values()))
        if index_mapping is None:
            return False
        properties = index_mapping.get("mappings", {}).get("properties", {})
        return field_name in properties

    def dispatch_chunks(self, chunks: list[DocumentChunk]) -> None:
        if not chunks:
            return

        for start in range(0, len(chunks), self.bulk_batch_size):
            batch = chunks[start : start + self.bulk_batch_size]
            operations = []
            for chunk in batch:
                operations.append(
                    {
                        "index": {
                            "_index": self.index_name,
                            "_id": chunk.chunk_id,
                        }
                    }
                )
                operations.append(chunk.model_dump(exclude_none=True))

            response = self._client.options(
                request_timeout=self.bulk_request_timeout_seconds,
                max_retries=self.bulk_max_retries,
                retry_on_timeout=True,
                retry_on_status=(429, 502, 503, 504),
            ).bulk(
                operations=operations,
                pipeline=self.pipeline_name,
                refresh="wait_for",
                timeout=self.bulk_api_timeout,
                wait_for_active_shards="1",
            )

            response_body = getattr(response, "body", response)
            if not response_body.get("errors", False):
                continue

            failed_items = [
                operation
                for item in response_body.get("items", [])
                for operation in item.values()
                if operation.get("error") is not None
            ]
            raise RuntimeError(
                "Elasticsearch bulk chunk dispatch failed for "
                f"{len(failed_items)} item(s): {failed_items[:3]}"
            )

    def dispatch_markdown(self, markdown: str) -> None:
        raise NotImplementedError
